name: python-analysis

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies with pip (flake8, mypy, and pygame)
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy pygame==2.1.3.dev4
    - name: Analysing the code with flake8 and mypy
      run: |
        flake8
        mypy $(git ls-files '*.py') --disallow-untyped-defs
